const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const users={Student:{id:'STU2026001',pass:'Edu@1234',name:'Rahul Sharma'},Admin:{id:'ADMIN2026',pass:'Admin@1234',name:'Administrator'}};
let role='Student';
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2600)}
function loginOpen(r){role=r;$('#loginTitle').textContent=r+' Login';$('#uid').value='';$('#pwd').value='';$('#demo').innerHTML='<b>Demo ID:</b> '+users[r].id+'<br><b>Password:</b> '+users[r].pass;$('#login').classList.add('show')}
$$('[data-login]').forEach(x=>x.onclick=()=>loginOpen(x.dataset.login));
$('#close').onclick=()=>$('#login').classList.remove('show');
$('#login').onclick=e=>{if(e.target.id==='login')$('#login').classList.remove('show')};
$('#loginBtn').onclick=()=>{let u=users[role];if($('#uid').value.trim()===u.id&&$('#pwd').value===u.pass){$('#login').classList.remove('show');showDashboard(role)}else toast('Invalid User ID or Password')};
function showDashboard(r){document.body.innerHTML=r==='Student'?studentDashboard():adminDashboard();window.scrollTo(0,0)}
function header(title){return `<header class="portal-header"><div class="wrap"><div class="pbrand"><img src="logo.png"><div><b>EduSrishti University</b><small>${title}</small></div></div><button class="logout" onclick="location.reload()">Logout</button></div></header>`}
function studentDashboard(){return `<div class="portal">${header('Student Digital Campus')}<div class="portal-layout"><aside class="side"><h3>Student Portal</h3><button>🏠 Dashboard</button><button>👤 My Profile</button><button>📚 My Course</button><button>💳 Fee Details</button><button>🧾 Payment History</button><button>📝 Exam Form</button><button>🏆 Results</button><button>✅ Attendance</button><button>📢 Notices</button><button>📜 Certificates</button><button>📁 Documents</button></aside><main class="portal-main"><div class="welcome"><div><span>STUDENT DASHBOARD</span><h1>Welcome, Rahul Sharma</h1><p>Enrollment: <b>ESU2026001</b> • BCA • Semester 3</p></div><button class="btn gold" onclick="toast('Demo payment screen. Connect a live gateway for real transactions.')">Pay Fees</button></div><div class="portal-cards"><div><small>Attendance</small><b>86%</b><span>Good standing</span></div><div><small>Current Semester</small><b>03</b><span>BCA</span></div><div><small>Pending Fees</small><b>₹0</b><span>All clear</span></div><div><small>Notices</small><b>07</b><span>Latest updates</span></div></div><div class="portal-box"><h2>Fee Summary</h2><table><tr><th>Fee Type</th><th>Amount</th><th>Status</th><th>Receipt</th></tr><tr><td>Tuition Fee</td><td>₹45,000</td><td><i>Paid</i></td><td>Download</td></tr><tr><td>Examination Fee</td><td>₹2,500</td><td><i>Paid</i></td><td>Download</td></tr><tr><td>Registration Fee</td><td>₹1,500</td><td><i>Paid</i></td><td>Download</td></tr></table></div><div class="portal-box"><h2>Academic Overview</h2><div class="overview"><div><b>8.2</b><span>CGPA</span></div><div><b>12</b><span>Subjects</span></div><div><b>4</b><span>Assignments</span></div><div><b>100%</b><span>Profile</span></div></div></div><div class="portal-box"><h2>Latest Notices</h2><p>📢 Examination schedule will be published in the portal.</p><p>📢 Keep your profile and documents updated.</p></div></main></div></div>`}
function adminDashboard(){return `<div class="portal">${header('University Administration Panel')}<div class="portal-layout"><aside class="side"><h3>Admin Panel</h3><button>📊 Dashboard</button><button>👥 Students</button><button>📝 Applications</button><button>📚 Courses</button><button>🏫 Departments</button><button>👨‍🏫 Faculty</button><button>💳 Fees & Payments</button><button>🧪 Examinations</button><button>🏆 Results</button><button>📢 Notices</button><button>🎓 Scholarships</button><button>📈 Reports</button><button>⚙️ Settings</button></aside><main class="portal-main"><div class="admin-banner"><span>ADMINISTRATION</span><h1>University Management Dashboard</h1><p>Central control for admissions, students, academics, fees, examinations and reports.</p></div><div class="portal-cards"><div><small>Total Students</small><b>4,820</b><span>Active records</span></div><div><small>New Applications</small><b>318</b><span>This session</span></div><div><small>Fee Collection</small><b>₹28.4L</b><span>Demo dashboard</span></div><div><small>Pending Fees</small><b>₹3.2L</b><span>Demo dashboard</span></div></div><div class="admin-modules"><div><b>👥 Student Management</b><span>Add, edit, search and view student records.</span></div><div><b>📝 Admission Management</b><span>Review applications and update statuses.</span></div><div><b>💳 Fees & Payments</b><span>Collections, dues, receipts and payment history.</span></div><div><b>📚 Academic Management</b><span>Courses, departments, semesters and curriculum.</span></div><div><b>👨‍🏫 Faculty Management</b><span>Faculty profiles, teaching and assignments.</span></div><div><b>🏆 Exams & Results</b><span>Schedules, marks, results and revaluation.</span></div><div><b>📢 Notice Board</b><span>Publish announcements and circulars.</span></div><div><b>📈 Reports</b><span>Admission, fee, student and academic reports.</span></div></div><div class="portal-box"><h2>Recent Applications</h2><table><tr><th>Application</th><th>Student</th><th>Course</th><th>Status</th></tr><tr><td>APP-26031</td><td>Aman Verma</td><td>BCA</td><td><i>Submitted</i></td></tr><tr><td>APP-26032</td><td>Priya Singh</td><td>BBA</td><td><i>Under Review</i></td></tr><tr><td>APP-26033</td><td>Mohit Kumar</td><td>B.Tech</td><td><i>Approved</i></td></tr></table></div></main></div></div>`}
$$('.course-tabs button').forEach(b=>b.onclick=()=>{$$('.course-tabs button').forEach(x=>x.classList.remove('active'));$$('.course-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.panel).classList.add('active')});
$('#menu').onclick=()=>$('#navlinks').classList.toggle('open');
$$('#navlinks a').forEach(a=>a.onclick=()=>$('#navlinks').classList.remove('open'));
$('#admissionForm').onsubmit=e=>{e.preventDefault();toast('Demo application submitted successfully.');e.target.reset()};
$('#contactForm').onsubmit=e=>{e.preventDefault();toast('Demo enquiry submitted successfully.');e.target.reset()};
$('#pay').onclick=()=>toast('Demo payment flow ready. No real payment is collected.');
